# Dependencies
gems:                [jekyll-paginate]
markdown:            kramdown
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               'bitburn.net'
tagline:             'by Peter Jay'
description:         'I am Peter: a developer, geek, travel and car enthusiast. This is my blog'
url:                 http://www.bitburn.net
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Peter Jankovics
  url:               https://twitter.com/iPeterJay
  email:             peter@bitburn.net

# Custom vars
version:             1.0.0

# Github repo
github:
  repo:              https://github.com/peterjay/peterjay.github.io

google_analytics:    UA-74717352-1