# Dependencies
markdown:            redcarpet
highlighter:         pygments
gems:                [jekyll-paginate]

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Peter Jankovics
tagline:             'A fairly technical personal blog'
description:         ''
url:                 http://www.bitburn.net
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Peter Jankovics
  url:               https://twitter.com/iPeterJay
  email:             peter@bitburn.net

# Custom vars
version:             1.0.0
